
services:
  db:
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpass"]
        interval: 5s
        timeout: 5s
        retries: 10
    image: mysql:8.0.33
    container_name: investimentos-db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: investimentos
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
      MYSQL_ROOT_HOST: '%'
      MYSQL_DEFAULT_CONNECT_TIMEOUT: 30
      MYSQL_WAIT_TIMEOUT: 28800
      MYSQL_INTERACTIVE_TIMEOUT: 28800
    ports:
      - '3307:3306'
    volumes:
      - investimentos-db:/var/lib/mysql
  
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: investimentos-backend
    ports:
      - "3333:3333"
    environment:
      DATABASE_URL: "mysql://user:userpass@db:3306/investimentos?schema=public"
      NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy
    

volumes:
  investimentos-db:
